In [1]:
# Classification template

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import os


In [2]:
CSV_File_Path = r'C:\Users\Sachin\Desktop\Udemy_Course_1\Deep Learning\Artificial_Neural_Networks\Churn_Modelling.csv'

if not os.path.exists(CSV_File_Path):
    CSV_File_Path = r'C:\Users\Sachin13390\Desktop\Udemy_Course_1\Deep Learning\Artificial_Neural_Networks\Churn_Modelling.csv'
  
if os.path.exists(CSV_File_Path):
    print (CSV_File_Path)
     

C:\Users\Sachin13390\Desktop\Udemy_Course_1\Deep Learning\Artificial_Neural_Networks\Churn_Modelling.csv


In [3]:
# Importing the dataset
dataset = pd.read_csv(CSV_File_Path)
# print (dataset)
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values

# print (X)

In [4]:
# Encoding categorical data
# Encoding the Independent Variable
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
# print (X)


In [5]:

labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
print (X)

[[619 0 0 ... 1 1 101348.88]
 [608 2 0 ... 0 1 112542.58]
 [502 0 0 ... 1 0 113931.57]
 ...
 [709 0 0 ... 0 1 42085.58]
 [772 1 1 ... 1 0 92888.52]
 [792 0 0 ... 1 0 38190.78]]


In [6]:
onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()

In [7]:
X = X[:, 1:]

In [8]:
# # Encoding the Dependent Variable
# labelencoder_y = LabelEncoder()
# y = labelencoder_y.fit_transform(y)

In [9]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection  import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

In [10]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)


In [11]:
X_train.shape

(8000, 11)

In [12]:
#######   PART 2 Building ANN

In [13]:
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout

d:\product\python36\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [14]:
# Initialze ANN
classifier = Sequential()

In [15]:
# Adding input layer and first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11 ))
classifier.add(Dropout(p = 0.10))

classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu' ))
classifier.add(Dropout(p = 0.10))

classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid' ))

d:\product\python36\lib\site-packages\ipykernel_launcher.py:3: UserWarning: Update your `Dropout` call to the Keras 2 API: `Dropout(rate=0.1)`
  This is separate from the ipykernel package so we can avoid doing imports until
d:\product\python36\lib\site-packages\ipykernel_launcher.py:6: UserWarning: Update your `Dropout` call to the Keras 2 API: `Dropout(rate=0.1)`
  


In [16]:
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [17]:
classifier.fit(X_train, y_train, batch_size = 10, epochs = 50)

Epoch 1/50
8000/8000 [==============================] - 3s 327us/step - loss: 0.4891 - acc: 0.7959
Epoch 2/50
8000/8000 [==============================] - 1s 114us/step - loss: 0.4293 - acc: 0.7960
Epoch 3/50
8000/8000 [==============================] - 1s 115us/step - loss: 0.4240 - acc: 0.7960
Epoch 4/50
8000/8000 [==============================] - 1s 114us/step - loss: 0.4209 - acc: 0.7960
Epoch 5/50
8000/8000 [==============================] - 1s 115us/step - loss: 0.4127 - acc: 0.8167
Epoch 6/50
8000/8000 [==============================] - 1s 115us/step - loss: 0.4099 - acc: 0.8259
Epoch 7/50
8000/8000 [==============================] - 1s 147us/step - loss: 0.4083 - acc: 0.8210
Epoch 8/50
8000/8000 [==============================] - 1s 128us/step - loss: 0.4077 - acc: 0.8211
Epoch 9/50
8000/8000 [==============================] - 1s 117us/step - loss: 0.4041 - acc: 0.8225
Epoch 10/50
8000/8000 [==============================] - 1s 118us/step - loss: 0.4085 - acc: 0.8166
Epoch 11/

In [ ]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)


In [ ]:

# Fitting classifier to the Training set
# Create your classifier here


# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [ ]:
cm

In [ ]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score

In [ ]:
def Build_Classifier():
    
    classifier = Sequential()
    
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11 ))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu' ))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid' ))
    
    classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    
    return classfier
    

In [ ]:
classifier = KerasClassifier(build_fn = Build_Classifier, batch_size = 10, nb_epoch = 100 )
accuracies = cross_val_score (estimator = classifier, X = X_train, y = y_train, cv = 10, n_jobs = -1 )

In [ ]:
print (accuracies)

In [ ]:
########################  Tunning  ANN

In [ ]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import GridSearchCV
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout

In [ ]:
def Build_Classifier(optimizer):
    
    classifier = Sequential()
    
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11 ))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu' ))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid' ))
    
    classifier.compile(optimizer = optimizer, loss = 'binary_crossentropy', metrics = ['accuracy'])
    
    return classifier

In [ ]:
classifier = KerasClassifier(build_fn = Build_Classifier )

In [ ]:
parameters = { 
                'batch_size' : [25, 32],
                'epochs' : [100, 500],
                'optimizer' : ['adam', 'rmsprop']
             }

In [ ]:
grid_search = GridSearchCV(estimator = classifier, 
                          param_grid = parameters,
                          scoring = 'accuracy',
                          cv = 1)


In [ ]:
grid_search = grid_search.fit(X_train,y_train)

In [ ]:
best_parameters = grid_search.best_params_

print ("Best Parameters " + str(best_parameters))


best_accuracy = grid_search.best_score_

print ("best_accuracy " + str(best_accuracy))